projects:
  app:
    schemPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4646
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: ../follow-api-service/prisma.yml